-- V5.3 - Categorização automática de produtos
-- Rode no Supabase SQL Editor.
-- A tabela products já possui a coluna category nas versões anteriores.

update public.products
set category = case
  when name ~* '(ALFACE|RUCULA|RÚCULA|TOMATE|BATATA|CEBOLA|ALHO|CENOURA|BANANA|MACA|MAÇÃ|LARANJA|LIMAO|LIMÃO|UVA|MANGA|ABACATE|ABACAXI|MELANCIA|MELAO|MELÃO|HORTIFRUTI|VERDURA|LEGUME)' then 'Hortifruti'
  when name ~* '(LEITE|IOGURTE|QUEIJO|MANTEIGA|REQUEIJAO|REQUEIJÃO|CREME DE LEITE|LEITE CONDENSADO|NATA|MUSSARELA|MOZZARELLA|PARMESAO|PARMESÃO)' then 'Laticínios'
  when name ~* '(ARROZ|FEIJAO|FEIJÃO|MACARRAO|MACARRÃO|MOLHO|OLEO|ÓLEO|AZEITE|FARINHA|ACUCAR|AÇUCAR|AÇÚCAR|CAFE|CAFÉ|SAL|TEMPERO|MILHO|ERVILHA|SARDINHA|ATUM|EXTRATO|BISCOITO|BOLACHA|PAO|PÃO|TORRADA|CEREAL|AVEIA|GRANOLA)' then 'Mercearia'
  when name ~* '(CARNE|FRANGO|LINGUICA|LINGUIÇA|PEIXE|BACON|PRESUNTO|MORTADELA|SALSICHA|HAMBURGUER|HAMBÚRGUER|PICANHA|ACEM|ACÉM|COXAO|COXÃO|PATINHO)' then 'Carnes e Frios'
  when name ~* '(CERVEJA|REFRIGERANTE|SUCO|AGUA|ÁGUA|ENERGETICO|ENERGÉTICO|VINHO|BEBIDA|CHA|CHÁ|COCA|GUARANA|GUARANÁ)' then 'Bebidas'
  when name ~* '(DETERGENTE|SABAO|SABÃO|AMACIANTE|DESINFETANTE|AGUA SANITARIA|ÁGUA SANITÁRIA|LIMPADOR|ESPONJA|VEJA|MULTIUSO|ALCOOL|ÁLCOOL|LAVA ROUPAS|LAVA-ROUPAS)' then 'Limpeza'
  when name ~* '(PAPEL HIGIENICO|PAPEL HIGIÊNICO|SABONETE|SHAMPOO|CONDICIONADOR|CREME DENTAL|PASTA DENTAL|ESCOVA|DESODORANTE|ABSORVENTE|FRALDA|HIGIENE)' then 'Higiene'
  when name ~* '(RACAO|RAÇÃO|PET|GATO|CAO|CÃO|CACHORRO|AREIA SANITARIA|AREIA SANITÁRIA)' then 'Pet'
  when name ~* '(SORVETE|PIZZA|LASANHA|CONGELADO|BATATA FRITA|NUGGET|HAMBURGUER CONG|POLPA)' then 'Congelados'
  else coalesce(category, 'Outros')
end
where category is null or category = '' or category = 'Outros';

-- Opcional: veja quantos produtos existem por categoria
select category, count(*)
from public.products
group by category
order by count(*) desc;
